/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package se.gustavkarlsson.gwiz.wizards;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import se.gustavkarlsson.gwiz.AbstractWizardPage;

/**
 *
 * @author adrianohrl
 */
public class EndPanel extends javax.swing.JPanel {
    
    private final AbstractWizardPage parent;
    
    /**
     * Creates new form EndPanel
     * 
     * @param parent
     */
    public EndPanel(final AbstractWizardPage parent) {
        this.parent = parent;
        initComponents();    
        finishTextField.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                parent.updateWizardButtons();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                parent.updateWizardButtons();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                parent.updateWizardButtons();
            }
        });
    } 
    
    public boolean saidYes() {
        return finishTextField.getText().trim().equalsIgnoreCase("yes");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        finishLabel = new javax.swing.JLabel();
        finishTextField = new javax.swing.JTextField();

        finishLabel.setText("Do you want to finish? Type in your answer:");

        finishTextField.setText("no");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(finishLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finishTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finishLabel)
                    .addComponent(finishTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(270, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel finishLabel;
    private javax.swing.JTextField finishTextField;
    // End of variables declaration//GEN-END:variables

}
